- name: common role msg-1
  debug:
    msg: "hi, i am from common role MSG-1" 

- name: common role msg-2
  debug:
    msg: "hi, i am from common role MSG-2 {{ item }}" 

- name: common role msg-3
  debug:
    msg: "hi, i am from common role MSG-3" 

- name: change the fact
  set_fact:    # to change the value of os from RedHat to Debian in the midddle of the playbook
    os: "Debian"  #overriding the pervious loaded variable

- name: common role msg-4
  debug:
    msg: "hi, i am from common role MSG-4" 

# - name: call role 2
#   include_role:  #include_role:
#     name: role-2
