- name: common role msg-1
  debug:
    msg: "hi, i am from common role MSG-1" 

- name: common role msg-2
  debug:
    msg: "hi, i am from common role MSG-2" 

- name: common role msg-3
  debug:
    msg: "hi, i am from common role MSG-3" 

- name: common role msg-4
  debug:
    msg: "hi, i am from common role MSG-4" 

- name: call role 2
  include_role:
    name: role-2
